### ISSUE TITLE
Linebreak, 0d0a, as a last character is not ignored as a difference.

### ISSUE THREAD

**Issue by PicayuneOne** [WinMerge/winmerge#989] opened 2021-09-28 16:48 UTC
If one file has a final linebreak and another does not, it always gets flagged as a difference even if "Ignore Whitespace" and "Ignore Blank Lines" are chosen.

**Comment by sdottaka** [comment] 2021-09-28 23:21
Duplicate of #203

**Comment by sdottaka** [comment] 2024-12-24 13:59
PR #2573 allows you to ignore differences where only one of the files does not have a trailing newline.

**Closed by sdottaka** 2024-12-24 13:59 UTC
Labels: Not a bug, Improvement needed, text compare/merge
