### ISSUE TITLE
Extreme tab height in maximized window

### ISSUE THREAD

**Issue by mommy742** [WinMerge/winmerge#2549] opened 2024-11-19 22:20 UTC
so when the window is maximized it does this.
![image](https://github.com/user-attachments/assets/492f0977-fb71-4e6f-8800-649e67573b66)
this only happens when its maximized and not any other way.
![image](https://github.com/user-attachments/assets/bd82c325-b798-47ff-a8b7-23ee616db73a)

i think this might happen to be a issue.

i can attach my configuration file if that helps

**Comment by sdottaka** [comment] 2024-11-19 23:18
Thank you for reporting this.
This issue has been resolved in commit https://github.com/WinMerge/winmerge/commit/e0f7a47c9364f3a5daad3a52c80b8940fa925895.

To work around it in version 2.16.44, you can:

    Uncheck View → Tab Bar → On Title Bar.
    Align the top position of the secondary monitor with the main monitor.

You can download the updated executable reflecting this fix from the link below.

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts
https://github.com/WinMerge/winmerge/actions/runs/11612459292/artifacts/2128254125

**Comment by sdottaka** [comment] 2024-11-19 23:18
Duplicate of https://github.com/WinMerge/winmerge/issues/2510

**Closed** 2024-11-19 23:20 UTC
Labels: bug, appearance
