### ISSUE TITLE
In windows 11 i have error 78 sidebyside with the winmerge manifest 

### ISSUE THREAD

**Issue by keaoner** [WinMerge/winmerge#1312] opened 2022-04-28 07:22 UTC
In windows 11 i have error 78 sideby side with the manifest 

here the error in event observer 

```
La création du contexte d’activation a échoué pour « C:\Program Files (x86)\WinMerge\WinMergeU.exe ». 
Erreur dans le fichier de manifeste ou de stratégie «  » à la ligne . 
Une version de composant nécessaire à l’application est en conflit avec une autre version de composant déjà active. 
Les composants en conflit sont : Composant 1 : C:\Windows\WinSxS\manifests\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_e541a94fcce8ed6d.manifest. Composant 2 : 
C:\Windows\WinSxS\manifests\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_9d947278b86cc467.manifest.
```

``` xml
[-](https://github.com/WinMerge/winmerge/discussions/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/WinMerge/winmerge/discussions/new#) <System>
  <Provider Name="SideBySide" /> 
  <EventID Qualifiers="49409">78</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-04-28T07:06:56.7878821Z" /> 
  <EventRecordID>3429</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="1036" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>skarla2</Computer> 
  <Security /> 
  </System>
[-](https://github.com/WinMerge/winmerge/discussions/new#) <EventData>
  <Data>C:\Windows\WinSxS\manifests\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_e541a94fcce8ed6d.manifest</Data> 
  <Data>C:\Windows\WinSxS\manifests\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_9d947278b86cc467.manifest</Data> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data>C:\Program Files (x86)\WinMerge\WinMergeU.exe</Data> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by sdottaka** [comment] 2022-05-21 15:34
I was unable to reproduce this problem, but I believe that commit f953b3c has removed the duplicated entries in the manifest, so the problem is no longer reproduced.

I close this issue.  Please reopen this issue if it reappears.

The latest build can be downloaded from the following URL:

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Closed by sdottaka** 2022-05-21 15:34 UTC
Labels: help wanted, stat:can't reproduce
