### ISSUE TITLE
50% cpu use by winmergeu.exe after program closed

### ISSUE THREAD

**Issue by Je55eah** [WinMerge/winmerge#903] opened 2021-07-28 21:46 UTC
Winmergeu.exe is hanging around long after the program was closed and taxing the processor for some reason. I installed the program today on a 32bit windows 7 system with the installer provided on your site today.
<img width="479" alt="20210728214156-2021-07-28 21_41_23-Windows Task Manager" src="https://user-images.githubusercontent.com/12481255/127400446-7027f91d-ea9c-4577-bddc-687353d19e57.png">

**Comment by sdottaka** [comment] 2021-07-28 22:29
I have tried on Windows XP, Windows 7, and Windows 10 and could not reproduce this problem.
Does this problem occur constantly on your machine?

In versions of WinMerge prior to 2.16.14, it was rare that closing the WinMerge window did not cause the process to terminate, and I am unable to find a correct solution to this problem.
As a workaround, WinMerge now kills its own process if the process does not terminate after two seconds from closing the window.

This may or may not be what is causing this problem. If you know of a way to reproduce this problem, please let me know.

**Comment by Je55eah** [comment] 2021-07-28 23:04
I killed the process then re-opened the files I was comparing. After closing WinMerge nothing remained. It's a spooky bug that I cannot reproduce.

**Comment by sdottaka** [comment] 2021-09-13 10:44
Fixed with commit 74a6f2f.
I was finally able to reproduce this issue on Windows 10 version 1809 on a virtual machine.

**Closed by sdottaka** 2021-09-13 10:44 UTC
Labels: bug, help wanted, need info

**Comment by Gitoffthelawn** [comment] 2022-01-23 04:41
What was causing this issue?  I seem to recall noticing it happen once several months ago.

**Comment by sdottaka** [comment] 2022-01-23 07:35
WinMerge has a thread that is responsible for asynchronously writing configuration data to the registry.
Write instructions are sent to this thread via a message queue, but in rare cases, the message queue is queued before it is fully created, which is what caused this issue.

**Comment by Gitoffthelawn** [comment] 2022-01-23 09:47
> WinMerge has a thread that is responsible for asynchronously writing configuration data to the registry. Write instructions are sent to this thread via a message queue, but in rare cases, the message queue is queued before it is fully created, which is what caused this issue.

Got it. Thank you!
