### ISSUE TITLE
Empty files are not copied

### ISSUE THREAD

**Issue by cassiusdrow** [WinMerge/winmerge#2146] opened 2023-12-19 19:06 UTC
In folder mode, empty (zero length) files are not copied when they do not exist on the target side.

**Comment by sdottaka** [comment] 2023-12-19 22:18
I couldn't reproduce this issue.
Which version of WinMerge are you using?
Could you please attach a screenshot of the state just before copying the empty files?

**Comment by cassiusdrow** [comment] 2023-12-22 00:06
It happens in both 2.16.34.0 and 2.16.36.0.  It only happens using binary contents compare mode.  All other modes work correctly.

**Steps to reproduce:**
1. Create two directories: "left" and "right"
2. In "left" directory, create a zero length file "empty1.txt", a file "test1.txt" containing "testing123", and a file "test2.txt" containing "testing123".
2. In "right" directory, create a zero length file "empty2.txt", a file "test1.txt" containing "testing456", and a file "test2.txt" containing "testing456".
4. Compare "left" directory to "right" directory using binary contents compare mode.
5. It correctly recognizes that the "test1.txt" and "test2.txt" files are different.
6. Select all files and use the "copy to right" or "copy to left" button on the toolbar.
7. The "Confirm Copy" dialog window says "Are you sure you want to copy 2 items?"
8. Clicking "yes" only copies the "test1.txt" and "test2.txt" files.

This zip file contains the above directories and files for testing:
[binary-copy-skips-empty-files.zip](https://github.com/WinMerge/winmerge/files/13746960/binary-copy-skips-empty-files.zip)

**Comment by sdottaka** [comment] 2023-12-22 12:59
Thank you for finding the conditions to reproduce. I am now able to reproduce the problem as well. This issue was fixed in commit 02436c0.

**Closed** 2023-12-24 00:05 UTC
Labels: bug, folder compare/merge
