### ISSUE TITLE
[UI] About WinMerge: information is gone after pressing Alt key => Alt + Print Screen is useless 

### ISSUE THREAD

**Issue by annazolkieve** [WinMerge/winmerge#404] opened 2020-08-11 18:23 UTC
![IMG_39_WINMERGE_BUG](https://user-images.githubusercontent.com/46918093/89934143-d0e1b480-dc18-11ea-86e3-5fe8eb5881ce.PNG)

**Comment by sdottaka** [comment] 2020-08-11 23:12
This seems to be a duplicate of issue #316.

**Closed by sdottaka** 2020-08-11 23:12 UTC
Labels: duplicate
