### ISSUE TITLE
“Match case” in Search always enabled

### ISSUE THREAD

**Issue by Dimoks** [WinMerge/winmerge#1380] opened 2022-06-26 05:59 UTC
![image](https://user-images.githubusercontent.com/3314441/175801471-09fd6df6-7c6b-4dcc-9793-0310c6de39d9.png)
In v 2.16.20.0 “Match case” always enabled, even if not checked.
Except for the case with “Regular expression” enabled.

**Comment by sdottaka** [comment] 2022-06-26 11:39
I tried the following but could not reproduce the problem.

![#1380](https://user-images.githubusercontent.com/98126/175812306-88a7e59a-abeb-437a-944a-4833c03dad70.gif)

Could you tell me if there is a way to reproduce it?

**Comment by Dimoks** [comment] 2022-06-26 19:51
Search Cyrillic text. For example «пролог» does not find «Пролог».

**Comment by sdottaka** [comment] 2022-06-27 11:57
Fixed in commit [b7af54e](https://github.com/WinMerge/winmerge/commit/b7af54ed59af2eb49fd1557b4e69b77a0f6fbcb8)
Thank you for the report.

**Closed by sdottaka** 2022-06-27 11:57 UTC
Labels: text compare/merge
