### ISSUE TITLE
Line by line comparison feature

### ISSUE THREAD

**Issue by pauvt** [WinMerge/winmerge#510] opened 2020-12-16 15:25 UTC
It be very useful to be to force winmerge to compare a text file contents line by line, rather than it try and auto align the differences.

In the following example I want to auto-merge the three files but winmerge can't because in some of the files I've added a new line.

![image](https://user-images.githubusercontent.com/58662223/102367577-388a8080-3fba-11eb-971b-4297e4e015c1.png)

Am I missing something or is this a bug/improvement?

**Comment by sdottaka** [comment] 2020-12-16 22:27
It's not a bug, but it needs improvement.

You can get the same result with the diff3 command.
kdiff3 (http://kdiff3.sourceforge.net/) seems to do this well.

**Comment by sdottaka** [comment] 2021-11-21 10:25
With the application of the PR #1051, the above example can now be auto-merged without conflicts when the 'Match similar lines' option is enabled.
![image](https://user-images.githubusercontent.com/98126/142758190-9624c9f5-9b55-4cc8-9dd6-2093a4c71a92.png)

**Closed by sdottaka** 2021-11-21 10:25 UTC
Labels: Improvement needed, 3-way compare/merge
