### ISSUE TITLE
[Command line] Bug: Command line bug when folder use space.

### ISSUE THREAD

**Issue by Ti-R** [WinMerge/winmerge#442] opened 2020-10-06 16:54 UTC
Platform Windows 7
WinMerge 2.16.8

Hello
It seems there is a bug with the command line when the path got a space.

eg:
This is working
"C:\Program Files (x86)\WinMerge\WinMergeU.exe" "C:\tmp" "C:\tmp\nospace"

This is not working
"C:\Program Files (x86)\WinMerge\WinMergeU.exe" "C:\tmp" "C:\tmp\name withspace"

_Result_
WinMerge open and tell
**First folder:**
C:\tmp

**Second Folder**
C:\tmp\name withspace"

**Right (2nd) path is invalid!**

Great software, great project !
Thx a lot if you got some times to look into it.

Renan

**Comment by sdottaka** [comment] 2020-10-06 21:47
I tried running it from the command prompt as below, but I couldn't reproduce this bug.

![image](https://user-images.githubusercontent.com/98126/95262353-f250cc80-0866-11eb-9bc7-2a42f319c72e.png)

How do you start WinMerge?

Also, what is displayed in the Command Line: line of the text file displayed from the Help → Configuration menu item?

When I run the above in my environment, I get the following:

Command Line: "C:\tmp" "C:\tmp\name with space"

If you get extra double quotes like the one below, WinMerge can't do anything about it because it was actually specified as such.

Command Line: "C:\tmp" "C:\tmp\name with space""

**Comment by Ti-R** [comment] 2020-11-02 22:50
Hello sdottaka.
Sorry to be that late to answer.
I was working on other functionalities.

I came back to test:
`"C:/Program Files (x86)/WinMerge/WinMergeU.exe" "C:\tmp\nospace\" "C:\tmp\name withspace\"`

It is true, the cmd line is working.
Sorry to have disturb you. I didn't try it raw from command line.

I was using "QProcess::startDetached" with the same command, I check again, and the result is not the same.
Launch with : `"\"C:/Program Files (x86)/WinMerge/WinMergeU.exe\" \"C:\\tmp\\nospace\\\" \"C:\\tmp\\name withspace\\\""`

And end up with OS call: `"C:\Program Files (x86)\WinMerge\WinMergeU.exe"  C:\tmp\nospace\ "C:\tmp\name withspace"\`

But If I launch with
`"\"C:/Program Files (x86)/WinMerge/WinMergeU.exe\" \"C:\\tmp\\nospace\" \"C:\\tmp\\name withspace\""`
This is working.

Anyway,

Thx a lot to look into the problem.
Have a good day.

Renan

**Comment by sdottaka** [comment] 2021-09-19 04:32
It does not seem to be a problem on the WinMerge side, so I will close it.

**Closed by sdottaka** 2021-09-19 04:32 UTC
Labels: need info, command line
