### ISSUE TITLE
Winmerge installs wrong in Chocolatey and winget

### ISSUE THREAD

**Issue by SamHills** [WinMerge/winmerge#426] opened 2020-09-09 20:59 UTC
When I install winmerge via the installer downloaded from the winmerge website, it installs to the correct directory.  But if I install it via Chocolatey or Micro$oft's new winget (which is very similar to Chocolatey), it installs winmerge to the current user's appdata directory.

**Comment by sdottaka** [comment] 2020-09-09 22:55
Chocolatey seems to be using WinMerge-2.16.8-x64-PerUser-Setup.exe, which is a per-user installation installer, rather than WinMerge-2.16.8-x64-Setup.exe.
(https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/winmerge/tools/chocolateyInstall.ps1#L7)

So it will be installed in the user's folder. Not a bug.

However, winget seems to always use the 32-bit version of the installer for all users.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/WinMerge/WinMerge/2.16.6.yaml

I'm not sure why that happens, but what if you uninstall and then reinstall?

**Closed** 2020-10-13 22:03 UTC
Labels: Not a bug
