### ISSUE TITLE
ALT-F4 opens Tools menu instead of exit from WinMerge

### ISSUE THREAD

**Issue by EMG60** [WinMerge/winmerge#2592] opened 2024-12-27 20:10 UTC
ALT-F4 opens Tools menu instead of exit from WinMerge

**Comment by sdottaka** [comment] 2024-12-27 22:27
In my environment, the Tools menu was displayed when I pressed Alt+F5. The cause of this is currently unknown. In your environment, does the Tools menu appear when you press Alt+F4 instead of Alt+F5?

**Comment by EMG60** [comment] 2024-12-28 09:26
Il 27/12/2024 23:28, Takashi Sawanaka ha scritto:

> In my environment, the Tools menu was displayed when I pressed Alt+F5. 
> The cause of this is currently unknown. In your environment, does the 
> Tools menu appear when you press Alt+F4 instead of Alt+F5?

Yes, exactly.

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

**Comment by sdottaka** [comment] 2024-12-29 01:52
This issue has been fixed in commit [e558227](https://github.com/WinMerge/winmerge/commit/e55822758e06db8a7dc5605de2dfa988f0d7d30a)
Thank you for your report.

**Closed by sdottaka** 2024-12-29 01:52 UTC
Labels: stat:awaiting response

**Comment by EMG60** [comment] 2024-12-29 08:16
Thank you! I will check it in the next official build.

**Comment by emil-prager** [comment] 2025-02-03 09:43
A small and less important completion, just for the sake of completeness.
<br />

> ALT-F4 opens Tools menu instead of exit from WinMerge

I could not reproduce that behaviour in version 2.16.44.
<br />


> In my environment, the Tools menu was displayed when I pressed Alt+F5.

In mine as well.
<br />


> This issue has been fixed in commit [e558227](https://github.com/WinMerge/winmerge/commit/e55822758e06db8a7dc5605de2dfa988f0d7d30a)

Before / after the mentioned fix, the Alt+F _x_ behaviour (for _x_ <= 12) is like this:

| Key    combination | Effect in 2.16.44 | Effect in 2.16.46 |
| --------------------- | ----------------- | ----------------- |
| Alt+F1 | Plugins | ∅ |
| Alt+F2 | ∅ | ∅ |
| Alt+F3 | ∅ | ∅ |
| Alt+F4 | File > Exit (Ctrl+Q) | File > Exit (Ctrl+Q) |
| Alt+F5 | Tools | ∅ |
| Alt+F6 | ∅ | ∅ |
| Alt+F7 | View | ∅ |
| Alt+F8 | Window | ∅ |
| Alt+F9 | ∅ | ∅ |
| Alt+F10 | ∅ | ∅ |
| Alt+F11 | ∅ | ∅ |
| Alt+F12 | ∅ | ∅ |

<br />
PS: It might have been interesting to test also the behaviour of the function keys above 12 (13-16), that are not present on the physical keyboards but for which there is a key code recognized by Windows.
<br />
(Pseudo keys like that are used by some programs to simulate key presses, especially because there is no risk of collision with actual keys pressings -- e.g. the [Move Mouse](https://github.com/sw3103/movemouse) project.)

**Comment by sdottaka** [comment] 2025-02-03 13:16
Thank you for the information.
In commit https://github.com/WinMerge/winmerge/commit/e55822758e06db8a7dc5605de2dfa988f0d7d30a, I have made it so that keys other than the Alt key and keys 0 to 9 or A to Z are ignored. Because of this, I think there will be no problem even if the F13 key is pressed.
