### ISSUE TITLE
Automatically scroll to first difference

### ISSUE THREAD

**Issue by mrLithe** [WinMerge/winmerge#452] opened 2020-10-14 11:40 UTC
Is it possible to make the program in the lower window also scroll the lines to first difference?

**Comment by sdottaka** [comment] 2020-10-14 12:53
You mean "When you enable the 'Automatically scroll to first difference' option, the upper window scrolls to the first difference, but the lower window, the Diff pane does not scroll to the first difference" ?

If so, I could not reproduce the problem.

![image](https://user-images.githubusercontent.com/98126/95989767-a7861480-0e65-11eb-8e27-6a9f817667df.png)

**Comment by mrLithe** [comment] 2020-10-15 05:19
Exactly. If the lines in the lower window are long, it only shows the beginning of the line. And the difference can be in the middle or at the end of the line.

**Comment by sdottaka** [comment] 2020-10-15 23:53
Does that mean that enabling the option causes vertical scrolling to the first difference line, but not horizontal scrolling to the inline differences within that line?

**Comment by mrLithe** [comment] 2020-10-16 05:27
Yes. Exactly.

**Comment by sdottaka** [comment] 2020-10-25 01:23
Fixed by commit d2d446f

**Closed by sdottaka** 2020-10-25 01:23 UTC

**Comment by Rukoto** [comment] 2020-11-16 05:46
@sdottaka 
Is it possible to allow the user to choose this behavior?
I like the previous behavior.

**Comment by sdottaka** [comment] 2020-11-16 23:23
I would think about it. What kind of behavior do you hate?
-Do you hate the caret moving to the first inline diff?
-Or do you hate scrolling to the first inline difference?

**Comment by Rukoto** [comment] 2020-11-17 03:36
-Or do you hate scrolling to the first inline difference?

Sometimes I just want to ignore the difference itself and only detect changes.
I don't want it to scroll horizontally every time I move to the next line.

**Comment by sdottaka** [comment] 2020-11-17 11:03
Thank you for your answer.

**Comment by sdottaka** [comment] 2020-11-21 06:31
Added "Automatically scroll to first inline diff" option in commit b16d6ce.

**Comment by Rukoto** [comment] 2020-11-22 04:49
Thank you, I appreciate it.
