### ISSUE TITLE
Performance using Unpacker

### ISSUE THREAD

**Issue by ajkajk** [WinMerge/winmerge#180] opened 2019-09-03 16:13 UTC
In order to compare video files,  I've written an unpacker plugin using MediaInfo ([https://mediaarea.net/en/MediaInfo](https://mediaarea.net/en/MediaInfo)) to generate an summary of properties and attributes.  The plugin works and provides text to be compared.

Unfortunately, before Winmerge compares and displays the text, it copies the source files to its temporary directory.  This happens after the call to MediaInfo,  which takes only a few hundred milliseconds to process the source files,  generating a few hundred characters for comparison.  For video files, that can be several gigabytes in size, the subsequent copy takes many seconds - over a minute for large file - and effectively makes the plugin unusable.

I can't think of any reason why the source files need to be copied before being overwritten with the generated text.  Would it be possible to avoid the copy?

**Comment by sdottaka** [comment] 2019-09-07 07:41
As you mentioned, when WinMerge compares text files, it creates files in the temporary folder while converting the text files to UTF-8.

However, I don't think WinMerge pass the source file that was copied to the temporary directory to the plugin.

I checked with CompareMSExcelFiles.sct plugin, but I couldn't confirm the behavior of copying the source file itself to a temporary directory before comparing with the plugin.

In your environment, is the temporary file path passed to the fileSrc argument of the UnpackFile method of the plugin ?

**Comment by ajkajk** [comment] 2019-09-07 15:30
I'm not suggesting that WinMerge passes copies of the files to the plugin.  Just that the source files are copied, and then discarded, **after** the plugin has processed them This takes a very very long time.

My plugin logs what it's asked to do.  Here's an example log comparing two video files.

**Extract from log maintained by plugin**
```
***Unpack first file
11:55:04.031 Entered UnpackFile: Source[C:\Users\ajk\Videos\iPlayer Recordings\1967.Don't Look Back.mp4] forCompare[C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\_WMB92C.tmp]
11:55:04.050 about to run:[cmd /c "MergePlugins\mediainfo.exe "C:\Users\ajk\Videos\iPlayer Recordings\1967.Don't Look Back.mp4" >> C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\_WMB92C.tmp 2>>&1"]
11:55:05.031 Run has returned:0
***Unpack second file
11:55:05.066 Entered UnpackFile: Source[C:\Users\ajk\Videos\8.03 The Long Night.mkv] forCompare[C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\_WMBD35.tmp]
11:55:05.066 about to run:[cmd /c "MergePlugins\mediainfo.exe "C:\Users\ajk\Videos\8.03 The Long Night.mkv" >> C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\_WMBD35.tmp 2>>&1"]
11:55:05.703 Run has returned:0
```
Here's an extract from ProcMon output for the same time, with my interpretation of what's happening.  This extract is for **after** the plugin has unpacked the files.
```
***Copy first file
11:55:05.7292393 ReadFile C:\Users\ajk\Videos\iPlayer Recordings\1967.Don't Look Back.mp4 SUCCESS Offset: 0, Length: 1,048,576, Priority: Normal
11:55:05.7296231 WriteFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t0_BFC6.tmp SUCCESS Offset: 0, Length: 1,048,576, Priority: Normal
<<<many similar lines>>>
11:56:54.4068984 ReadFile C:\Users\ajk\Videos\iPlayer Recordings\1967.Don't Look Back.mp4 SUCCESS Offset: 3,549,429,760, Length: 816,272
11:56:54.4074412 WriteFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t0_BFC6.tmp SUCCESS Offset: 3,549,429,760, Length: 816,272

***Copy second file
11:56:54.4657664 ReadFile C:\Users\ajk\Videos\8.03 The Long Night.mkv SUCCESS Offset: 0, Length: 1,048,576, I/O Flags: Non-cached, Paging I/O, Priority: Normal
11:56:54.4965555 WriteFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t1_6866.tmp SUCCESS Offset: 0, Length: 1,048,576, Priority: Normal
<<<many similar lines>>>
11:58:46.2291836 ReadFile C:\Users\ajk\Videos\8.03 The Long Night.mkv SUCCESS Offset: 5,297,405,952, Length: 487,164
11:58:46.2298780 WriteFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t1_6866.tmp SUCCESS Offset: 5,297,405,952, Length: 487,164

***Overwrite copy of first file with text for display
11:58:46.4047991 CreateFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t0_BFC6.tmp SUCCESS Desired Access: Generic Read/Write, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: None, AllocationSize: 0, OpenResult: Overwritten
11:58:46.4055014 WriteFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t0_BFC6.tmp SUCCESS Offset: 0, Length: 4,096, Priority: Normal
11:58:46.4057489 WriteFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t0_BFC6.tmp SUCCESS Offset: 4,096, Length: 1,047, Priority: Normal
11:58:46.4058611 CloseFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t0_BFC6.tmp SUCCESS 

***Overwrite copy of second file with text for display
11:58:46.4089063 CreateFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t1_6866.tmp SUCCESS Desired Access: Generic Read/Write, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: None, AllocationSize: 0, OpenResult: Overwritten
11:58:46.4609404 WriteFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t1_6866.tmp SUCCESS Offset: 0, Length: 3,953, Priority: Normal
11:58:46.4612635 CloseFile C:\Users\ajk\AppData\Local\Temp\WinMerge_TEMP_7812\t1_6866.tmp SUCCESS
``` 
Hope this makes sense.  As you can see, for this example, copying the two video files takes over three minutes.  Transforming the files takes less than two minutes.

**Comment by ajkajk** [comment] 2019-09-07 15:33
"Transforming the files takes less than two minutes."
Oooops!! I meant of course "Transforming the files takes less than two **seconds**".

**Comment by sdottaka** [comment] 2019-09-08 04:40
Hmm, I still cannot reproduce the problem.
I think your plugin failed to get information about video files correctly.
Could you try the attached plugin script, please?

[CompareMediaInfo.zip](https://github.com/WinMerge/winmerge/files/3587289/CompareMediaInfo.zip)

**Comment by ajkajk** [comment] 2019-09-08 09:45
That's odd.  Not sure what you mean about getting file information correctly.  

In any event, using your plugin gives exactly the same result.  Mediainfo runs twice, and then the source files are copied before the comparison results are displayed.  

The plugin is essentially the same as mine.

Is there anything more I can do?  The winMergeU.exe says it is 2.16.5.0 X64.  Is it worth downloading afresh and re-installing?  If so, which version would you recommend?

As an aside the regread call in your plugin doesn't return anything by the way, and not sure I understand the filefilter - it seems to allow the extension in the middle of filename.

**Comment by sdottaka** [comment] 2019-09-09 00:08
I tested with version 2.16.4 x64 and the latest version (2.16.5).

> Not sure what you mean about getting file information correctly.

Sorry for not enough explanation.
If the unpacker plugin fails the unpacking process, WinMerge will compare the source file itself, not the file created by unpacking. I thought it might be this.

> As an aside the regread call in your plugin doesn't return anything by the way

Does WinMerge correctly compare the information generated by mediainfo.exe when using your plugin?

My plugin produces the following results:
![#180](https://user-images.githubusercontent.com/98126/64496554-15662100-d2e1-11e9-97ca-14cf532b9622.gif)

**Comment by ajkajk** [comment] 2019-09-09 07:04
Yes - my plugin displays the correct results. The only issue is the delay when comparing large files e.g. Gigabytes. The unpacker returns true to indicate success. It successfully runs mediainfo. 
The videos you are comparing are quite small and with a fast file system won't  delay the display of the comparison results much. Perhaps you could try tracing IO activity using procmon. (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to see if the input files are copied on your system?

**Comment by sdottaka** [comment] 2019-09-09 23:20
Sorry to bother you.
Certainly, when I look at the log of procmon, it looks like a lot of reads and writes are occurring.
I'll look at it later.

**Comment by sdottaka** [comment] 2019-09-13 23:02
Fixed by commit 31884e0 

The latest CI build artifacts are available at:
https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Closed by sdottaka** 2019-09-13 23:02 UTC

**Comment by ajkajk** [comment] 2019-09-16 09:28
I've tried the new build in my environment, and the video comparison now appears promptly.  Thank you.

**Comment by sdottaka** [comment] 2019-09-16 23:03
Thank you for the confirmation.
