### ISSUE TITLE
The last blank line is not ignored

### ISSUE THREAD

**Issue by btnlq** [WinMerge/winmerge#203] opened 2019-10-09 06:58 UTC
**WinMerge 2.16.4.0 x64**

Program is configured to ignore whitespace, but:
- Last blank line is not ignored.
- `Text3` lines are highlighted as different.

![image](https://user-images.githubusercontent.com/31797752/66457703-cc95b980-ea92-11e9-94c7-ef1b812467e0.png)

**Comment by keviniles-tandf** [comment] 2021-07-12 15:58
This is almost a year old, has there been any movement on this?

**Comment by sambartle** [comment] 2021-09-10 08:07
Is there any known workaround for this?

It flags just about every file for some of our projects due to a code cleaner adding a carriage return at the end of the file.

**Comment by marcinhordziej** [comment] 2022-02-11 14:44
Still an issue - makes comparing much more complicated on huge amount of files.

**Comment by JasperTeng** [comment] 2022-10-26 08:39
I agree this should be fixed. most modern systems are able to handle texts without a blank last line. There is no need to highlight it specifically. If the concern is to maintain backward compatibility, maybe it can be added as an additional option.
e.g.:
[X] Ignore blank lines [_] including last line.

**Comment by sambartle** [comment] 2022-10-26 11:30
It's a critical bug in my eyes.. as the ignore whitespace option basically doesn't work. 
I switched to a BC for this reason as its marked as Not a bug.. indicating its intentional.

**Comment by TFWol** [comment] 2024-04-21 05:09
Yes, this is still annoying.

**Comment by sdottaka** [comment] 2024-12-24 13:58
PR #2573 allows you to ignore differences where only one of the files does not have a trailing newline.

**Closed by sdottaka** 2024-12-24 13:58 UTC
Labels: Not a bug, Improvement needed, text compare/merge
