### ISSUE TITLE
HTML Report Generation ERROR

### ISSUE THREAD

**Issue by RAJUPROP** [WinMerge/winmerge#791] opened 2021-05-17 10:53 UTC
After comparing the files and if we try to generate Report as HTML , WinMerge closes prematurely and no reports were generated. But, no problem with text or xml formats Report generation . This issue is seen on versions from 2.16.9 to 2.16.12 , for Windows 10 (64-bit).

**Comment by sdottaka** [comment] 2021-05-17 13:31
I couldn't reproduce this issue.
Please let me know if there are any conditions that can be reproduced.

**Comment by RAJUPROP** [comment] 2021-05-17 14:20
![WM_01](https://user-images.githubusercontent.com/40003035/118504329-089dff80-b749-11eb-9b23-e108a8e9925a.jpg)
![WM_02](https://user-images.githubusercontent.com/40003035/118504357-0e93e080-b749-11eb-9b58-aa2d5a032d58.jpg)

**Comment by RAJUPROP** [comment] 2021-05-17 15:11
However, older versions upto v2.14.x are working fine in generating HTML report. But, v2.16.x (both 32 & 64 bits) show errors and closes the program while generating HTML report (File Comparison result). But. other formats like Tab separated, Comma separated, Simple XML do not show any error....

**Comment by RAJUPROP** [comment] 2021-05-17 15:13
![Report](https://user-images.githubusercontent.com/40003035/118512367-5cf8ad80-b750-11eb-84f8-aa2adb728ef6.jpg)

**Comment by RAJUPROP** [comment] 2021-05-18 08:16
Conditions that can be reproduced
---------------------------------------
When the list of entries (No. of items) to be exported as simple HTML is MORE THAN 25 , the above issue occurs in versions 2.16.x.

**Comment by sdottaka** [comment] 2022-06-19 09:58
PR #1319 fixed a crash when creating an HTML report. This fix will be included in 2.16.21, which will be released on 2022-06-20.
So I close this issue.
If you still have problems with this version, please reopen this issue.

**Closed by sdottaka** 2022-06-19 09:58 UTC
Labels: bug, help wanted, need info, crash, stat:can't reproduce
