### ISSUE TITLE
can folders be asymmetric to find and compare similarly named files regardless of their location?

### ISSUE THREAD

**Issue by blank-teer** [WinMerge/winmerge#1978] opened 2023-08-11 16:48 UTC
for example:
A\B\file.txt <> A\file.txt

**Comment by sdottaka** [comment] 2023-08-11 23:13
Unfortunately WinMerge doesn't have such a feature.

**Comment by sdottaka** [comment] 2023-08-11 23:33
Duplicate of #1957

**Closed by sdottaka** 2023-08-11 23:33 UTC
Labels: question, folder compare/merge
