### ISSUE TITLE
Column order is wrong.

### ISSUE THREAD

**Issue by PicayuneOne** [WinMerge/winmerge#990] opened 2021-09-28 16:58 UTC
Using newly install v2.14.16.0
Diffing only on dates.
Columns in table of differences has Right Date column and then Left Date.
These columns are in the wrong order (Left Date needs to be to the left.)
Capisce?

**Comment by PicayuneOne** [comment] 2021-09-28 17:20
Even more nuisanceful when diffing on file contents.

**Comment by sdottaka** [comment] 2021-09-28 23:18
I have not been able to reproduce this problem.

To make the Left Date column appear to the left of the Right Date column, drag the header as shown below.

![990](https://user-images.githubusercontent.com/98126/135178256-15450714-c811-4250-bdda-6ec60d8a46f9.gif)

**Comment by sdottaka** [comment] 2022-03-19 06:09
For now, it looks like no one else has encountered this problem. Perhaps you accidentally dragged the header and the order changed. So I close this issue. If this problem reappears, please reopen it.

**Closed by sdottaka** 2022-03-19 06:09 UTC
Labels: folder compare/merge, stat:can't reproduce
