### ISSUE TITLE
Installation -  Internal error: Failed to expand shell folder constant "userdesktop"

### ISSUE THREAD

**Issue by CodyMathis123** [WinMerge/winmerge#354] opened 2020-06-04 12:10 UTC
WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe running under system context throws the error below. I see the use of SHGetFolderPath which is deprecate, but I don't see that in the source code for the application. See the following link regarding the method being deprecated. https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpatha 

Warning: SHGetFolderPath failed with code 0x80070002 on folder 0x8010

See the attached log file for more context. Typically, the installation will succeed on the second run. 

[WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe_.log](https://github.com/WinMerge/winmerge/files/4729806/WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe_.log)

**Comment by sdottaka** [comment] 2020-06-05 13:25
According to the logs, it looks like you are installing WinMerge silently using software like System Center Configuration Manager instead of the usual way.
Is this my guess correct?

When I do a silent installation with administrative privileges, I get the following log output.

~~~
2020-06-05 22:08:00.493   Log opened. (Time zone: UTC+09:00)
2020-06-05 22:08:00.493   Setup version: Inno Setup version 5.6.1 (u)
2020-06-05 22:08:00.493   Original Setup EXE: c:\dev\winmerge\Build\Releases\WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe
2020-06-05 22:08:00.493   Setup command line: /SL5="$151FCA,6798723,121344,c:\dev\winmerge\Build\Releases\WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe" /VERYSILENT /NOCLOSEAPPLICATIONS /NORESTARTAPPLICATIONS /NORESTART /SP- /SUPPRESSMSGBOXES /LOG=C:\tmp\WinMerge-2.16.6-x64-Setup_no_support_for_per-user_installation.exe.log
2020-06-05 22:08:00.493   Windows version: 10.0.19041  (NT platform: Yes)
2020-06-05 22:08:00.493   64-bit Windows: Yes
2020-06-05 22:08:00.493   Processor architecture: x64
2020-06-05 22:08:00.493   User privileges: Administrative
2020-06-05 22:08:00.501   64-bit install mode: Yes
2020-06-05 22:08:00.508   Created temporary directory: C:\Users\sawan\AppData\Local\Temp\is-EP6BD.tmp
2020-06-05 22:08:00.516   -- DLL function import --
2020-06-05 22:08:00.516   Function name: GetSysColor
2020-06-05 22:08:00.516   DLL name: user32.dll
2020-06-05 22:08:00.516   Dest DLL name: user32.dll
2020-06-05 22:08:00.516   Importing the DLL function.
2020-06-05 22:08:00.516   Successfully imported the DLL function. Delay loaded? No
2020-06-05 22:08:01.376   Starting the installation process.
2020-06-05 22:08:01.432   Directory for uninstall files: C:\Program Files\WinMerge
....
~~~

One interesting difference from your log is that the Created temporary directory line in your log does not include the user's name.
Perhaps the account that installs WinMerge is not the same account that performs the usual GUI operations.
So I assume it is a failed attempt to get the desktop folder path.

Install as a normal user or pull requests are welcome.

**Comment by CodyMathis123** [comment] 2020-07-02 03:17
Correct, this is from an SCCM based deployment. 

I was trying to find in the repo where you are calling the method, to potentially make a pull request, but I could not find the reference to SHGetFolderPath.

**Comment by sdottaka** [comment] 2020-08-10 01:12
I haven't tested it, but I fixed the installer to avoid accessing the {userdesktop}, so I think this issue will be resolved.

**Comment by DW-42** [comment] 2020-12-11 01:41
Unfortunately I am able to replicate the issue with WinMerge-2.16.8-Setup.exe

```
2020-12-11 11:34:02.720   Log opened. (Time zone: UTC+10:00)
2020-12-11 11:34:02.720   Setup version: Inno Setup version 5.5.9 (u)
2020-12-11 11:34:02.720   Original Setup EXE: C:\WINDOWS\ccmcache\q\WinMerge-2.16.8-Setup.exe
2020-12-11 11:34:02.720   Setup command line: /SL5="$C05BA,6541741,121344,C:\WINDOWS\ccmcache\q\WinMerge-2.16.8-Setup.exe" /VERYSILENT /NORESTART /NOCANCEL /ALLUSERS /NOFORCECLOSEAPPLICATIONS /LOG="C:\Temp\InstallationLogs\WinMerge\2.16.8\\WinMerge-2.16.8-Setup.log"  
2020-12-11 11:34:02.720   Windows version: 10.0.18362  (NT platform: Yes)
2020-12-11 11:34:02.721   64-bit Windows: Yes
2020-12-11 11:34:02.721   Processor architecture: x64
2020-12-11 11:34:02.721   User privileges: Administrative
2020-12-11 11:34:02.727   64-bit install mode: No
2020-12-11 11:34:02.732   Created temporary directory: C:\WINDOWS\TEMP\is-5IQTL.tmp
2020-12-11 11:34:03.029   Warning: SHGetFolderPath failed with code 0x80070002 on folder 0x8010
2020-12-11 11:34:03.029   Exception message:
2020-12-11 11:34:03.029   Message box (OK):
                          Internal error: Failed to expand shell folder constant "userdesktop"
2020-12-11 11:34:14.307   User chose OK.
2020-12-11 11:34:14.307   Deinitializing Setup.
2020-12-11 11:34:14.310   Log closed.
```

**Comment by sdottaka** [comment] 2020-12-12 10:32
WinMerge-2.16.8-Setup.exe has not been fixed, so could you please try WinMerge-2.16.8-x64-setup.exe?

**Comment by DW-42** [comment] 2020-12-13 05:30
I can confirm that WinMerge-2.16.8-x64-setup.exe works correctly (both as a  User with Administrator rights and as the built in "NT AUTHORITY\SYSTEM" account. 
Thank you for your time.

```
2020-12-13 15:23:11.169   Log opened. (Time zone: UTC+10:00)
2020-12-13 15:23:11.169   Setup version: Inno Setup version 5.5.9 (u)
2020-12-13 15:23:11.169   Original Setup EXE: C:\WINDOWS\ccmcache\x\WinMerge-2.16.8-x64-Setup.exe
2020-12-13 15:23:11.169   Setup command line: /SL5="$D0696,7154350,121344,C:\WINDOWS\ccmcache\x\WinMerge-2.16.8-x64-Setup.exe" /VERYSILENT /NORESTART /NOCANCEL /ALLUSERS /NOFORCECLOSEAPPLICATIONS /LOG="C:\Temp\InstallationLogs\WinMerge\2.16.8.0\\WinMerge-2.16.8-x64-Setup.log"  
2020-12-13 15:23:11.169   Windows version: 10.0.18362  (NT platform: Yes)
2020-12-13 15:23:11.170   64-bit Windows: Yes
2020-12-13 15:23:11.170   Processor architecture: x64
2020-12-13 15:23:11.170   User privileges: Administrative
2020-12-13 15:23:11.175   64-bit install mode: Yes
2020-12-13 15:23:11.180   Created temporary directory: C:\WINDOWS\TEMP\is-SS8HQ.tmp
2020-12-13 15:23:11.859   Starting the installation process.
2020-12-13 15:23:11.872   Directory for uninstall files: C:\Program Files\WinMerge
2020-12-13 15:23:11.875   Will append to existing uninstall log: C:\Program Files\WinMerge\unins000.dat
2020-12-13 15:23:11.877   -- File entry --
2020-12-13 15:23:11.877   Dest filename: C:\Program Files\WinMerge\unins000.exe
2020-12-13 15:23:11.877   Non-default bitness: 32-bit
2020-12-13 15:23:11.879   Time stamp of our file: 2020-12-13 15:23:10.878
2020-12-13 15:23:11.879   Dest file exists.
2020-12-13 15:23:11.879   Time stamp of existing file: 2020-12-13 13:26:36.161
2020-12-13 15:23:11.879   Version of our file: 51.1052.0.0
2020-12-13 15:23:11.880   Version of existing file: 51.1052.0.0
2020-12-13 15:23:11.880   Installing the file.
```

...etc

**Comment by sdottaka** [comment] 2021-09-19 04:03
The latest installer should not have this problem for both 32bit and 64bit versions, so I am closing this issue.

Please reopen when it reappears.

**Closed by sdottaka** 2021-09-19 04:03 UTC
Labels: installer
