### ISSUE TITLE
Reloading file does not refresh its encoding

### ISSUE THREAD

**Issue by Moatassem** [WinMerge/winmerge#466] opened 2020-10-24 23:23 UTC
Hi,

If you have a text file that uses encoding UTF-8 with BOM for instance, but you do update its encoding to be without BOM from external application like Notepad++, WinMerge indeed notifies that one file has changed, but when it refreshes it, it just keeps the old encoding .. although if you close WinMerge and reopen the changed file, it will read its current encoding properly.

BR,
Moatassem

**Comment by sdottaka** [comment] 2020-10-25 01:08
What version of WinMerge are you using?
This issue should have been fixed in version 2.16.7.

Duplicate of #320

**Comment by Moatassem** [comment] 2020-10-25 17:44
I'm actually using v2.16.8 and the bug is still there

**Comment by sdottaka** [comment] 2020-10-26 12:10
Sorry. I thought this problem couldn't be reproduced, but now I've reproduced it and fixed it. (Fixed by commit 537cfe3)
Thank you for your report.

**Closed by sdottaka** 2020-10-26 12:10 UTC
