### ISSUE TITLE
Failure to indent lines properly

### ISSUE THREAD

**Issue by timint** [WinMerge/winmerge#1740] opened 2023-03-02 11:21 UTC
I have the setting to use 2 spaces indentation. I am often having troubles selecting a block of text/code, and while pressing TAB it is only indenting one space character.

I had the suspicion this happens when there is greyish line in the middle of the selected blocks. I have been able to produce it with this example where indenting the right block produces only 1 space indentation.

LEFT
```
    
  line a
  line b
  line c
```

RIGHT
```
  line a
  line b
  line c
```

The expected behavior is that all  selected lines should be indented 2 spaces when I press tab.

**Comment by sdottaka** [comment] 2023-03-02 14:16
I tried like the animated GIF below, but I couldn't reproduce the problem. Please let me know if there are conditions for reproduction.

![#1740](https://user-images.githubusercontent.com/98126/222452619-275966fe-3628-4ca1-b3a0-a37809a7974b.gif)

**Comment by timint** [comment] 2023-03-03 09:38
I copied my own example above and you are right, it wouldn't reproduce. So I just opened a random file instead:
![Animation](https://user-images.githubusercontent.com/359192/222684793-6e9f454f-eebf-4fd9-9d59-8fd0993786d7.gif)
![image](https://user-images.githubusercontent.com/359192/222685057-5b1ac5d4-1ee9-4acf-ba84-18e2a18ae0af.png)

I have this issue in almost every file I am working with. From a third up to half my attempts ends up this way.

**Comment by sdottaka** [comment] 2023-03-03 13:54
Thank you for attaching the video.
I think I was able to reproduce this issue. I'll look into it later.

**Comment by timint** [comment] 2023-03-03 16:31
Ooh this is good news 🙂👍

**Comment by sdottaka** [comment] 2023-03-04 00:42
This seems to occur when the current caret column position is 2, 4, 6, ....

This is fixed in commit https://github.com/WinMerge/winmerge/commit/632b158b5ac64b3e39aeb27b4ac0de4f3e2194bc.

The CI build artifact can be downloaded from the following URL

https://ci.appveyor.com/project/sdottaka/winmerge/build/artifacts

**Closed** 2023-03-15 00:00 UTC
Labels: editlib
