### ISSUE TITLE
"Ignore comment differences" still compares inline comments

### ISSUE THREAD

**Issue by JustinReinhart** [WinMerge/winmerge#2008] opened 2023-09-01 22:31 UTC
Issue:
Inline comments (end of line comments) should be ignored when user enables "Ignore comment differences". Currently WinMerge still marks these lines as different when the actual code is the same. 

Example: 
`   if ((WindowWidth >= Buffer->Width * 2) && // If display can support a 2x scale full screen`
    
^ Here the comment "If display can support a 2x scale full screen" line is highlighted in orange and red, even though user has chosen to ignore comment differences.

What should happen:
WinMerge should not include the comment for comparison per user preference. The line should not trigger orange and red highlighting because the code to the left of the comment is the same in both files.
   
Use case:
User is taking a course with new source code released every day. User wants to keep their own comments but still diff/compare/merge daily course installments one line at a time.

**Comment by sdottaka** [comment] 2023-09-02 00:57
Perhaps there is also a difference one line above or one line below the line shown in the example?
If so, unfortunately if there is another difference within the block of diff where the comment you want to ignore exists, the difference in that block will not be ignored. This is something I think needs improvement.
If not, I can't reproduce this problem, so
Could you please post a screenshot?

**Comment by JustinReinhart** [comment] 2023-09-02 02:28
Screenshot attached as requested.  Note: If I move the comment to its own line, the compare resolves and the comment becomes a gentle cream color as desired. Issue persists if I put the comment back at the end of the line.

![2023-09-01 Bug inline comment highlighting](https://github.com/WinMerge/winmerge/assets/2589841/320a97cd-6b17-4135-ab85-53f28ab2904f)

![2023-09-01 WinMerge Options](https://github.com/WinMerge/winmerge/assets/2589841/4d3d2720-bb2c-47d4-babc-0b878ca1f4f8)

**Comment by sdottaka** [comment] 2023-09-03 01:48
Thank you for providing the screenshot. I have been able to reproduce this issue (I couldn't reproduce it before because I hadn't tried it without inline comments in the other file). I have fixed it in commit 7a0b9a9, so I will now close this issue.

**Closed by sdottaka** 2023-09-03 01:48 UTC
